import { chromium } from 'playwright-core';
import { mkdir } from 'node:fs/promises';
await mkdir('artifacts', { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const assert = (v, msg) => { if (!v) throw new Error(msg); };
await page.goto('http://127.0.0.1:5173');
await page.getByRole('button', { name: '开始使用' }).click();
await page.getByRole('button', { name: '添加早上的任务' }).click();
await page.getByRole('textbox', { name: '任务标题', exact: true }).fill('每天 9点 阅读一本好书 p1');
await page.getByRole('button', { name: '添加任务', exact: true }).click();
await page.getByRole('button', { name: '添加下午的任务' }).click();
await page.getByRole('textbox', { name: '任务标题', exact: true }).fill('整理本周的学习笔记');
await page.getByRole('button', { name: '添加任务', exact: true }).click();
await page.getByRole('button', { name: '添加晚上的任务' }).click();
await page.getByRole('textbox', { name: '任务标题', exact: true }).fill('散步三十分钟 @生活');
await page.getByRole('button', { name: '添加任务', exact: true }).click();
await page.getByRole('button', { name: '标记为完成', exact: true }).first().click();
await page.getByRole('button', { name: '标记为未完成', exact: true }).click();
await page.getByRole('button', { name: '标记为完成', exact: true }).first().click();
await page.reload();
await page.getByRole('heading', { name: '今天', exact: true }).waitFor();
const tasks = await page.evaluate(async () => (await import('/src/db.ts')).loadAll().then(s => s.tasks));
assert(tasks.length === 4, 'one recurring successor, persisted');
assert(tasks.some(t => t.dueTime === '09:00' && t.repeat), 'time and repeat preserved');
await page.getByRole('button', { name: '下一周', exact: true }).click();
assert(await page.locator('.week-day.sel').count() === 1, 'selected day follows week');
await page.getByRole('button', { name: '回到今天' }).click();
await page.getByRole('button', { name: '待办', exact: true }).click();
await page.locator('.task-row.done').waitFor({ state: 'detached' });
assert(await page.locator('.task-row.done').count() === 0, 'pending filter');
await page.getByRole('button', { name: '全部', exact: true }).click();
await page.keyboard.press('Control+k');
await page.getByPlaceholder('搜索任务、备注或标签…').fill('学习');
assert(await page.locator('.search-results .task-row').count() === 1, 'search');
await page.keyboard.press('Escape');
await page.screenshot({ path: 'artifacts/desktop-light.png', fullPage: true });
await page.getByRole('button', { name: '添加早上的任务' }).click();
await page.keyboard.press('Shift+Tab');
assert(await page.evaluate(() => !!document.activeElement.closest('[role="dialog"]')), 'dialog focus trapped');
await page.keyboard.press('Escape');
await page.getByRole('button', { name: '设置', exact: true }).first().click();
await page.getByRole('button', { name: '深色', exact: true }).click();
await page.getByRole('button', { name: '今天', exact: false }).first().click();
await page.screenshot({ path: 'artifacts/desktop-dark.png', fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true });
assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile overflow');
for (const label of ['计划', '洞察', '设置']) {
  await page.locator('.bottom-nav').getByRole('button', { name: label, exact: true }).click();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), label + ' overflow');
}
await page.getByRole('button', { name: '浅色', exact: true }).click();
await page.locator('.bottom-nav').getByRole('button', { name: '今天', exact: true }).click();
await page.emulateMedia({ reducedMotion: 'reduce' });
assert(await page.locator('.main-inner').evaluate(el => getComputedStyle(el).animationName) === 'none', 'reduced motion');
await page.setViewportSize({ width: 320, height: 740 });
assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '320px overflow');
assert(!errors.length, JSON.stringify(errors));
console.log(JSON.stringify({ passed: true, tasks: tasks.length, errors, checks: ['recurrence', 'persistence', 'quick input', 'calendar', 'filters', 'search', 'focus', 'themes', 'mobile routes', '320px', 'reduced motion'] }));
await browser.close();
